import {
  LayoutDashboard,
  Users,
  Building2,
  CalendarCheck,
  Clock,
  CalendarOff,
  Banknote,
  Gift,
  Target,
  GraduationCap,
  UserPlus,
  UserCheck,
  LogOut,
  Files,
  BarChart4,
  Megaphone,
  UserCog,
  ShieldCheck,
  Settings2,
  FileKey,
  Webhook,
  Bot,
  Scale,
  HelpCircle,
  FileSignature
} from 'lucide-react';

export interface SubMenu {
  title: string;
  slug: string;
  route: string;
  permissionKey: string;
}

export interface NavItem {
  id: string;
  label: string;
  slug: string;
  icon: any; // using any for Lucide icon component type simplicity
  group: 'main' | 'administration' | 'support';
  route?: string;
  subItems?: SubMenu[];
  permissionKey: string;
  badgeCount?: number;
}

const toSlug = (value: string) =>
  value
    .toLowerCase()
    .trim()
    .replace(/&/g, 'and')
    .replace(/[\/]/g, '-')
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

const makeSubItems = (basePath: string, titles: string[], permissionPrefix: string): SubMenu[] =>
  titles.map((title) => {
    const slug = toSlug(title);
    return {
      title,
      slug,
      route: `${basePath}/${slug}`,
      permissionKey: `${permissionPrefix}.${slug}`,
    };
  });

export const navigationConfig: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    slug: 'dashboard',
    icon: LayoutDashboard,
    group: 'main',
    permissionKey: 'hris.dashboard',
    subItems: makeSubItems('/dashboard', [
      'Executive HR Dashboard',
      'HR Operations Dashboard',
      'Employee Workforce Summary',
      'Attendance Snapshot',
      'Leave Snapshot',
      'Payroll Snapshot',
      'Recruitment Snapshot',
      'Training Snapshot',
      'Alerts & Notifications',
      'Quick Actions',
      'Pending Approvals',
      'HR Calendar',
      'Compliance Summary',
    ], 'hris.dashboard'),
  },
  {
    id: 'employees',
    label: 'Employees',
    slug: 'employees',
    icon: Users,
    group: 'main',
    route: '/employees',
    permissionKey: 'hris.employees',
    subItems: makeSubItems('/employees', [
      'Employee Directory',
      'Employee Profile Management',
      'Employee Lifecycle',
      'Employee Documents',
      'Employee Movements',
      'Employee Exit Management',
      'Employee Reports',
    ], 'hris.employees'),
  },
  {
    id: 'organization',
    label: 'Organization',
    slug: 'organization',
    icon: Building2,
    group: 'main',
    permissionKey: 'hris.organization',
    subItems: makeSubItems('/organization', [
      'Company Structure',
      'Departments',
      'Units / Sections',
      'Locations / Sites',
      'Job Grades',
      'Job Titles',
      'Reporting Hierarchy',
      'Organogram',
      'Position Management',
      'Workforce Planning',
      'Headcount Planning',
      'Vacancy Management',
    ], 'hris.organization'),
  },
  {
    id: 'attendance',
    label: 'Attendance',
    slug: 'attendance',
    icon: CalendarCheck,
    group: 'main',
    permissionKey: 'hris.attendance',
    subItems: makeSubItems('/attendance', [
      'Daily Attendance',
      'Clock-In / Clock-Out',
      'Biometric Attendance',
      'Mobile Attendance',
      'Site Attendance',
      'Attendance Register',
      'Late Arrival Tracking',
      'Early Departure Tracking',
      'Absence Tracking',
      'Overtime Attendance',
      'Shift Attendance',
      'Attendance Exceptions',
      'Attendance Approval',
      'Attendance Reports',
    ], 'hris.attendance'),
  },
  {
    id: 'time-and-logs',
    label: 'Time & Logs',
    slug: 'time-and-logs',
    icon: Clock,
    group: 'main',
    permissionKey: 'hris.time-and-logs',
    subItems: makeSubItems('/time-and-logs', [
      'Timesheet Entry',
      'Timesheet Approval',
      'Project Time Logs',
      'Department Time Logs',
      'Field Work Logs',
      'Overtime Logs',
      'Shift Logs',
      'Work Schedule',
      'Roster Management',
      'Time Correction Requests',
      'Supervisor Review',
      'Timesheet Reports',
    ], 'hris.time-and-logs'),
  },
  {
    id: 'leave-management',
    label: 'Leave Management',
    slug: 'leave-management',
    icon: CalendarOff,
    group: 'main',
    permissionKey: 'hris.leave-management',
    subItems: makeSubItems('/leave-management', [
      'Leave Dashboard',
      'Leave Application',
      'Leave Approval',
      'Leave Calendar',
      'Leave Balance',
      'Annual Leave',
      'Sick Leave',
      'Maternity Leave',
      'Paternity Leave',
      'Compassionate Leave',
      'Study Leave',
      'Casual Leave',
      'Unpaid Leave',
      'Leave Recall',
      'Leave Cancellation',
      'Leave Encashment',
      'Leave Policy Setup',
      'Leave Reports',
    ], 'hris.leave-management'),
  },
  {
    id: 'payroll',
    label: 'Payroll Management',
    slug: 'payroll-management',
    icon: Banknote,
    group: 'main',
    permissionKey: 'hris.payroll',
    route: '/payroll-management',
    subItems: makeSubItems('/payroll-management', [
      'Dashboard',
      'Salary Management',
      'Earnings Management',
      'Deductions Management',
      'Payroll Processing',
      'Compliance & Statutory Management',
      'Bank Payments & Finance Integration',
      'Reports & Analytics',
    ], 'hris.payroll'),
  },
  {
    id: 'benefits',
    label: 'Benefits',
    slug: 'benefits',
    icon: Gift,
    group: 'main',
    permissionKey: 'hris.benefits',
    subItems: makeSubItems('/benefits', [
      'Benefit Plans',
      'Medical Benefits',
      'Insurance Benefits',
      'Pension Benefits',
      'Staff Welfare',
      'Allowance Benefits',
      'Benefit Eligibility',
      'Benefit Enrollment',
      'Benefit Claims',
      'Benefit Approval',
      'Benefit Reports',
    ], 'hris.benefits'),
  },
  {
    id: 'performance-management',
    label: 'Performance Management',
    slug: 'performance-management',
    icon: Target,
    group: 'main',
    permissionKey: 'hris.performance-management',
    subItems: makeSubItems('/performance-management', [
      'Performance Dashboard',
      'KPI Setup',
      'Appraisal Cycles',
      'Employee Goals',
      'Department Goals',
      'Supervisor Review',
      'Self-Appraisal',
      '360-Degree Review',
      'Competency Assessment',
      'Performance Scorecard',
      'Promotion Recommendation',
      'Performance Improvement Plan',
      'Performance Reports',
    ], 'hris.performance-management'),
  },
  {
    id: 'learning-and-development',
    label: 'Learning & Development',
    slug: 'learning-and-development',
    icon: GraduationCap,
    group: 'main',
    permissionKey: 'hris.learning-and-development',
    subItems: makeSubItems('/learning-and-development', [
      'Training Dashboard',
      'Training Calendar',
      'Training Needs Assessment',
      'Course Catalogue',
      'Training Requests',
      'Training Approval',
      'Training Attendance',
      'Certifications',
      'Skills Matrix',
      'Mandatory Training',
      'External Training',
      'Training Budget',
      'Training Evaluation',
      'Learning Reports',
    ], 'hris.learning-and-development'),
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    slug: 'recruitment',
    icon: UserPlus,
    group: 'main',
    permissionKey: 'hris.recruitment',
    subItems: makeSubItems('/recruitment', [
      'Recruitment Dashboard',
      'Manpower Request',
      'Job Requisition',
      'Job Posting',
      'Candidate Database',
      'Application Screening',
      'Interview Scheduling',
      'Interview Evaluation',
      'Offer Management',
      'Background Checks',
      'Recruitment Approval',
      'Talent Pool',
      'Recruitment Reports',
    ], 'hris.recruitment'),
  },
  {
    id: 'onboarding',
    label: 'Onboarding',
    slug: 'onboarding',
    icon: UserCheck,
    group: 'main',
    permissionKey: 'hris.onboarding',
    subItems: makeSubItems('/onboarding', [
      'Onboarding Dashboard',
      'New Hire Checklist',
      'Document Collection',
      'Offer Acceptance',
      'Employee Account Creation',
      'Department Assignment',
      'Equipment Request',
      'Induction Schedule',
      'Policy Acknowledgement',
      'Probation Setup',
      'Onboarding Progress',
      'Onboarding Reports',
    ], 'hris.onboarding'),
  },
  {
    id: 'offboarding',
    label: 'Offboarding',
    slug: 'offboarding',
    icon: LogOut,
    group: 'main',
    permissionKey: 'hris.offboarding',
    subItems: makeSubItems('/offboarding', [
      'Resignation Management',
      'Exit Clearance',
      'Handover Checklist',
      'Asset Return',
      'Final Payroll Processing',
      'Exit Interview',
      'Access Deactivation',
      'Benefits Closure',
      'Certificate / Reference Letter',
      'Exit Approval',
      'Offboarding Reports',
    ], 'hris.offboarding'),
  },
  {
    id: 'documents-and-records',
    label: 'Documents & Records',
    slug: 'documents-and-records',
    icon: Files,
    group: 'main',
    permissionKey: 'hris.documents-and-records',
    subItems: makeSubItems('/documents-and-records', [
      'Employee Documents',
      'HR Policies',
      'Contract Letters',
      'Appointment Letters',
      'Promotion Letters',
      'Query Letters',
      'Warning Letters',
      'Training Certificates',
      'Medical Records',
      'Payroll Documents',
      'Compliance Documents',
      'Document Expiry Alerts',
      'Document Approval',
      'Document Archive',
    ], 'hris.documents-and-records'),
  },
  {
    id: 'reports-and-analytics',
    label: 'Reports & Analytics',
    slug: 'reports-and-analytics',
    icon: BarChart4,
    group: 'main',
    permissionKey: 'hris.reports-and-analytics',
    subItems: makeSubItems('/reports-and-analytics', [
      'Workforce Reports',
      'Attendance Reports',
      'Leave Reports',
      'Payroll Reports',
      'Recruitment Reports',
      'Training Reports',
      'Performance Reports',
      'Turnover Reports',
      'Compliance Reports',
      'Department Reports',
      'Management Reports',
      'Custom Report Builder',
      'Export to Excel / PDF',
      'Scheduled Reports',
    ], 'hris.reports-and-analytics'),
  },
  {
    id: 'announcements',
    label: 'Announcements',
    slug: 'announcements',
    icon: Megaphone,
    group: 'main',
    permissionKey: 'hris.announcements',
    subItems: makeSubItems('/announcements', [
      'HR Announcements',
      'Company Notices',
      'Policy Updates',
      'Event Announcements',
      'Birthday Notices',
      'Work Anniversary Notices',
      'Department Notices',
      'Emergency Notices',
      'Announcement Approval',
      'Announcement Archive',
    ], 'hris.announcements'),
  },
  {
    id: 'user-management',
    label: 'User Management',
    slug: 'user-management',
    icon: UserCog,
    group: 'administration',
    permissionKey: 'hris.admin.user-management',
    subItems: makeSubItems('/administration/user-management', [
      'User Accounts',
      'Create User',
      'Edit User',
      'Disable User',
      'Reset Password',
      'User Profile',
      'User Department Assignment',
      'Login History',
      'Account Lockout',
      'User Activity Log',
      'Super Admin Account Control',
    ], 'hris.admin.user-management'),
  },
  {
    id: 'roles-and-permissions',
    label: 'Roles & Permissions',
    slug: 'roles-and-permissions',
    icon: ShieldCheck,
    group: 'administration',
    permissionKey: 'hris.admin.roles-and-permissions',
    subItems: makeSubItems('/administration/roles-and-permissions', [
      'Role Management',
      'Permission Matrix',
      'Menu Access Control',
      'Page Access Control',
      'Approval Access Control',
      'Department-Based Access',
      'Location-Based Access',
      'Payroll Access Control',
      'Sensitive Data Access',
      'Delegated Access',
      'Temporary Access',
      'Segregation of Duties',
    ], 'hris.admin.roles-and-permissions'),
  },
  {
    id: 'approval-workflow',
    label: 'Approval Workflow',
    slug: 'approval-workflow',
    icon: FileSignature,
    group: 'administration',
    permissionKey: 'hris.admin.approval-workflow',
    subItems: makeSubItems('/administration/approval-workflow', [
      'Approval Matrix',
      'Leave Approval Workflow',
      'Payroll Approval Workflow',
      'Recruitment Approval Workflow',
      'Training Approval Workflow',
      'Document Approval Workflow',
      'Timesheet Approval Workflow',
      'Multi-Level Approval',
      'Delegated Approval',
      'Escalation Rules',
      'Approval SLA',
      'Approval Audit Trail',
    ], 'hris.admin.approval-workflow'),
  },
  {
    id: 'system-settings',
    label: 'System Settings',
    slug: 'system-settings',
    icon: Settings2,
    group: 'administration',
    permissionKey: 'hris.admin.system-settings',
    subItems: makeSubItems('/administration/system-settings', [
      'Company Profile',
      'HR Policy Configuration',
      'Department Setup',
      'Location Setup',
      'Job Grade Setup',
      'Job Title Setup',
      'Leave Policy Setup',
      'Payroll Settings',
      'Attendance Settings',
      'Email Settings',
      'Notification Settings',
      'Security Settings',
      'Backup Settings',
      'Numbering Format',
      'System Preferences',
    ], 'hris.admin.system-settings'),
  },
  {
    id: 'audit-trail',
    label: 'Audit Trail',
    slug: 'audit-trail',
    icon: FileKey,
    group: 'administration',
    permissionKey: 'hris.admin.audit-trail',
    subItems: makeSubItems('/administration/audit-trail', [
      'User Activity Logs',
      'Login Logs',
      'Data Change Logs',
      'Approval Logs',
      'Payroll Change Logs',
      'Employee Record Logs',
      'Permission Change Logs',
      'Document Access Logs',
      'Failed Login Attempts',
      'Export Logs',
      'Compliance Audit Reports',
    ], 'hris.admin.audit-trail'),
  },
  {
    id: 'integrations',
    label: 'Integrations',
    slug: 'integrations',
    icon: Webhook,
    group: 'administration',
    permissionKey: 'hris.admin.integrations',
    subItems: makeSubItems('/administration/integrations', [
      'Biometric Device Integration',
      'Payroll Bank Integration',
      'Microsoft 365 Integration',
      'Google Workspace Integration',
      'Email Integration',
      'SMS Gateway',
      'ERP Integration',
      'Sage Integration',
      'Accounting System Integration',
      'Active Directory Integration',
      'API Management',
      'Webhooks',
      'Integration Logs',
    ], 'hris.admin.integrations'),
  },
  {
    id: 'ai-and-automation',
    label: 'AI & Automation',
    slug: 'ai-and-automation',
    icon: Bot,
    group: 'administration',
    permissionKey: 'hris.admin.ai-and-automation',
    subItems: makeSubItems('/administration/ai-and-automation', [
      'HR AI Assistant',
      'Employee Risk Prediction',
      'Attendance Anomaly Detection',
      'Leave Pattern Analysis',
      'Payroll Error Detection',
      'Attrition Prediction',
      'Recruitment Matching',
      'Training Recommendation',
      'Performance Insight Engine',
      'Compliance Alerts',
      'Automated HR Reminders',
      'Smart Workforce Forecasting',
    ], 'hris.admin.ai-and-automation'),
  },
  {
    id: 'compliance-and-governance',
    label: 'Compliance & Governance',
    slug: 'compliance-and-governance',
    icon: Scale,
    group: 'administration',
    permissionKey: 'hris.admin.compliance-and-governance',
    subItems: makeSubItems('/administration/compliance-and-governance', [
      'Labour Law Compliance',
      'NDPR Data Privacy',
      'Employee Consent Records',
      'Policy Acknowledgement',
      'Disciplinary Records',
      'Grievance Management',
      'Health & Safety Compliance',
      'Compliance Calendar',
      'Regulatory Reports',
      'Internal Control Checklist',
      'HR Risk Register',
    ], 'hris.admin.compliance-and-governance'),
  },
  {
    id: 'help-and-support',
    label: 'Help & Support',
    slug: 'help-and-support',
    icon: HelpCircle,
    group: 'support',
    permissionKey: 'hris.support.help-and-support',
    route: '/support/help-desk',
    subItems: makeSubItems('/support', [
      'Help Desk',
      'HR Support Tickets',
      'FAQs',
      'User Guide',
      'Training Videos',
      'System Support',
      'Feedback',
      'Issue Reporting',
      'Change Requests',
      'Support Reports',
    ], 'hris.support.help-and-support'),
  },
];
